/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.bbva.evalua.swing.view.jframe;

import java.awt.FlowLayout;
import javax.swing.JComponent;
import javax.swing.TransferHandler;

public class CV0205v01JFrameJLabelDragDrogJLabel extends javax.swing.JFrame {

    public CV0205v01JFrameJLabelDragDrogJLabel() {
        initComponents();
       this.setTitle("JFrame Swing with Drag and Drop and mousePressed");
       this.setSize(700, 200);
       this.setLayout(new FlowLayout());
       this.setLocationRelativeTo(this);
        //2.0 especificamos qué tipo de dato vamos a transferir
        
        jLabelTextoArrastrar.setTransferHandler(new TransferHandler("text"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelArrastrar = new javax.swing.JPanel();
        jLabelTextoArrastrar = new javax.swing.JLabel();
        jTextFieldTextoArrastrado = new javax.swing.JTextField();
        jTextFieldTextoArrastrado1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTextoArrastrar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTextoArrastrar.setText("El texto del JLabel arrastrar a jTextField");
        jLabelTextoArrastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelTextoArrastrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelArrastrarLayout = new javax.swing.GroupLayout(jPanelArrastrar);
        jPanelArrastrar.setLayout(jPanelArrastrarLayout);
        jPanelArrastrarLayout.setHorizontalGroup(
            jPanelArrastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArrastrarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTextoArrastrar)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelArrastrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelArrastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldTextoArrastrado)
                    .addComponent(jTextFieldTextoArrastrado1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );
        jPanelArrastrarLayout.setVerticalGroup(
            jPanelArrastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArrastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTextoArrastrar)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTextoArrastrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTextoArrastrado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelArrastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelArrastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTextoArrastrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoArrastrarMousePressed
        
        System.out.println(evt);
        JComponent jc = (JComponent)evt.getSource();
        TransferHandler th = jc.getTransferHandler();
        th.exportAsDrag(jc, evt, TransferHandler.COPY);
    }//GEN-LAST:event_jLabelTextoArrastrarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CV0205v01JFrameJLabelDragDrogJLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CV0205v01JFrameJLabelDragDrogJLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CV0205v01JFrameJLabelDragDrogJLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CV0205v01JFrameJLabelDragDrogJLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CV0205v01JFrameJLabelDragDrogJLabel().setVisible(true);
            }
        });
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTextoArrastrar;
    private javax.swing.JPanel jPanelArrastrar;
    private javax.swing.JTextField jTextFieldTextoArrastrado;
    private javax.swing.JTextField jTextFieldTextoArrastrado1;
    // End of variables declaration//GEN-END:variables
}
