/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.aemsa.evalua.swing.view.jdialog;

import java.awt.Point;


public class CV0104v01JDialogReservaCancha extends javax.swing.JDialog {

    /**
     * Creates new form CV0104v01JDialogReservaCancha
     */
    public CV0104v01JDialogReservaCancha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupHorario = new javax.swing.ButtonGroup();
        jPanelCancha = new javax.swing.JPanel();
        jButtonCancha01 = new javax.swing.JButton();
        jButtonCancha02 = new javax.swing.JButton();
        jButtonCancha03 = new javax.swing.JButton();
        jButtonCancha04 = new javax.swing.JButton();
        jButtonCancha05 = new javax.swing.JButton();
        jButtonCancha06 = new javax.swing.JButton();
        jButtonCanhca07 = new javax.swing.JButton();
        jButtonCancha08 = new javax.swing.JButton();
        jButtonCancha09 = new javax.swing.JButton();
        jButtonCancha10 = new javax.swing.JButton();
        jButtonCancha11 = new javax.swing.JButton();
        jButtonCancha12 = new javax.swing.JButton();
        jButtonCancha13 = new javax.swing.JButton();
        jButtonCancha14 = new javax.swing.JButton();
        jButtonCancha15 = new javax.swing.JButton();
        jButtonCancha16 = new javax.swing.JButton();
        jButtonCancha17 = new javax.swing.JButton();
        jPanelHorarioPorCancha = new javax.swing.JPanel();
        jToggleButtonHora1 = new javax.swing.JToggleButton();
        jToggleButtonHora2 = new javax.swing.JToggleButton();
        jToggleButtonHora3 = new javax.swing.JToggleButton();
        jToggleButtonHora4 = new javax.swing.JToggleButton();
        jToggleButtonHora5 = new javax.swing.JToggleButton();
        jToggleButtonHora6 = new javax.swing.JToggleButton();
        jToggleButtonHora8 = new javax.swing.JToggleButton();
        jToggleButtonHora7 = new javax.swing.JToggleButton();
        jToggleButtonHora9 = new javax.swing.JToggleButton();
        jToggleButtonHora10 = new javax.swing.JToggleButton();
        jToggleButtonHora11 = new javax.swing.JToggleButton();
        jToggleButtonHora12 = new javax.swing.JToggleButton();
        jToggleButtonHora13 = new javax.swing.JToggleButton();
        jToggleButtonHora14 = new javax.swing.JToggleButton();
        jToggleButtonHora15 = new javax.swing.JToggleButton();
        jToggleButtonHora16 = new javax.swing.JToggleButton();
        jToggleButtonHora17 = new javax.swing.JToggleButton();
        jToggleButtonHora18 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelCancha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButtonCancha01.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha01.setText("Cancha 01");
        jButtonCancha01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancha01ActionPerformed(evt);
            }
        });

        jButtonCancha02.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha02.setText("Cancha 02");
        jButtonCancha02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancha02ActionPerformed(evt);
            }
        });

        jButtonCancha03.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha03.setText("Cancha 03");
        jButtonCancha03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancha03ActionPerformed(evt);
            }
        });

        jButtonCancha04.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha04.setText("Cancha 04");
        jButtonCancha04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancha04ActionPerformed(evt);
            }
        });

        jButtonCancha05.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha05.setText("Cancha 05");
        jButtonCancha05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancha05ActionPerformed(evt);
            }
        });

        jButtonCancha06.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha06.setText("Cancha 06");

        jButtonCanhca07.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCanhca07.setText("Cancha 07");

        jButtonCancha08.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha08.setText("Cancha 08");

        jButtonCancha09.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha09.setText("Cancha 09");

        jButtonCancha10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha10.setText("Cancha 10");

        jButtonCancha11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha11.setText("Cancha 11");

        jButtonCancha12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha12.setText("Cancha 12");

        jButtonCancha13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha13.setText("Cancha 13");

        jButtonCancha14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha14.setText("Cancha 14");

        jButtonCancha15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha15.setText("Cancha 15");

        jButtonCancha16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha16.setText("Cancha 16");

        jButtonCancha17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancha17.setText("Cancha 17");

        javax.swing.GroupLayout jPanelCanchaLayout = new javax.swing.GroupLayout(jPanelCancha);
        jPanelCancha.setLayout(jPanelCanchaLayout);
        jPanelCanchaLayout.setHorizontalGroup(
            jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCanchaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCanchaLayout.createSequentialGroup()
                        .addComponent(jButtonCanhca07, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancha08, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCanchaLayout.createSequentialGroup()
                        .addGroup(jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonCancha03, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCancha01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addComponent(jButtonCancha05, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCancha02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCancha04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCancha06, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCanchaLayout.createSequentialGroup()
                        .addComponent(jButtonCancha09, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancha10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCanchaLayout.createSequentialGroup()
                        .addComponent(jButtonCancha11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancha12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCanchaLayout.createSequentialGroup()
                        .addComponent(jButtonCancha13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancha14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCanchaLayout.createSequentialGroup()
                        .addComponent(jButtonCancha15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancha16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonCancha17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCanchaLayout.setVerticalGroup(
            jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCanchaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancha01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancha02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancha03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancha04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancha05, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancha06, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCanhca07, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancha08, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancha09, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancha10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancha11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancha12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancha13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancha14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancha15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancha16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancha17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelHorarioPorCancha.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder())));

        buttonGroupHorario.add(jToggleButtonHora1);
        jToggleButtonHora1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora1.setText("06 - 07 a.m.");
        jToggleButtonHora1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jToggleButtonHora1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jToggleButtonHora1MouseMoved(evt);
            }
        });
        jToggleButtonHora1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonHora1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButtonHora1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButtonHora1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButtonHora1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jToggleButtonHora1MouseReleased(evt);
            }
        });

        buttonGroupHorario.add(jToggleButtonHora2);
        jToggleButtonHora2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora2.setText("07 - 08 a.m.");

        buttonGroupHorario.add(jToggleButtonHora3);
        jToggleButtonHora3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora3.setText("08 - 09 a.m.");

        buttonGroupHorario.add(jToggleButtonHora4);
        jToggleButtonHora4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora4.setText("09 - 10 a.m.");

        buttonGroupHorario.add(jToggleButtonHora5);
        jToggleButtonHora5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora5.setText("10 - 11 a.m.");

        buttonGroupHorario.add(jToggleButtonHora6);
        jToggleButtonHora6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora6.setText("11 - 12 a.m.");

        buttonGroupHorario.add(jToggleButtonHora8);
        jToggleButtonHora8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora8.setText("13 - 14 p.m.");

        buttonGroupHorario.add(jToggleButtonHora7);
        jToggleButtonHora7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora7.setText("12 - 13 p.m.");

        buttonGroupHorario.add(jToggleButtonHora9);
        jToggleButtonHora9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora9.setText("14 - 15 p.m.");

        buttonGroupHorario.add(jToggleButtonHora10);
        jToggleButtonHora10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora10.setText("15 - 16 p.m.");

        buttonGroupHorario.add(jToggleButtonHora11);
        jToggleButtonHora11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora11.setText("16 - 17 p.m.");

        buttonGroupHorario.add(jToggleButtonHora12);
        jToggleButtonHora12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora12.setText("17 - 18 p.m.");

        buttonGroupHorario.add(jToggleButtonHora13);
        jToggleButtonHora13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora13.setText("18 - 19 p.m.");

        buttonGroupHorario.add(jToggleButtonHora14);
        jToggleButtonHora14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora14.setText("19 - 20 p.m.");

        buttonGroupHorario.add(jToggleButtonHora15);
        jToggleButtonHora15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora15.setText("20 - 21 p.m.");

        buttonGroupHorario.add(jToggleButtonHora16);
        jToggleButtonHora16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora16.setText("21 - 22 p.m.");

        buttonGroupHorario.add(jToggleButtonHora17);
        jToggleButtonHora17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora17.setText("22 - 23 p.m.");

        buttonGroupHorario.add(jToggleButtonHora18);
        jToggleButtonHora18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToggleButtonHora18.setText("23 - 24 p.m.");

        javax.swing.GroupLayout jPanelHorarioPorCanchaLayout = new javax.swing.GroupLayout(jPanelHorarioPorCancha);
        jPanelHorarioPorCancha.setLayout(jPanelHorarioPorCanchaLayout);
        jPanelHorarioPorCanchaLayout.setHorizontalGroup(
            jPanelHorarioPorCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHorarioPorCanchaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHorarioPorCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHorarioPorCanchaLayout.createSequentialGroup()
                        .addComponent(jToggleButtonHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHorarioPorCanchaLayout.createSequentialGroup()
                        .addComponent(jToggleButtonHora3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonHora4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHorarioPorCanchaLayout.createSequentialGroup()
                        .addComponent(jToggleButtonHora5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonHora6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHorarioPorCanchaLayout.createSequentialGroup()
                        .addComponent(jToggleButtonHora7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonHora8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHorarioPorCanchaLayout.createSequentialGroup()
                        .addComponent(jToggleButtonHora9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonHora10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHorarioPorCanchaLayout.createSequentialGroup()
                        .addComponent(jToggleButtonHora11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonHora12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHorarioPorCanchaLayout.createSequentialGroup()
                        .addComponent(jToggleButtonHora13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonHora14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHorarioPorCanchaLayout.createSequentialGroup()
                        .addComponent(jToggleButtonHora15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonHora16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHorarioPorCanchaLayout.createSequentialGroup()
                        .addComponent(jToggleButtonHora17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonHora18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHorarioPorCanchaLayout.setVerticalGroup(
            jPanelHorarioPorCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHorarioPorCanchaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHorarioPorCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHorarioPorCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonHora3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonHora4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHorarioPorCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonHora5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonHora6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHorarioPorCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonHora7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonHora8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHorarioPorCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonHora9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonHora10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHorarioPorCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonHora11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonHora12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHorarioPorCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonHora13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonHora14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHorarioPorCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonHora15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonHora16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHorarioPorCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonHora17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonHora18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHorarioPorCancha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHorarioPorCancha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancha01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancha01ActionPerformed

        jToggleButtonHora1.setBackground(java.awt.Color.RED);
        jToggleButtonHora2.setBackground(java.awt.Color.BLUE);
        jToggleButtonHora3.setBackground(java.awt.Color.GRAY);
        jToggleButtonHora4.setBackground(java.awt.Color.GREEN);
        jToggleButtonHora5.setBackground(java.awt.Color.DARK_GRAY);
        
        jToggleButtonHora6.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora7.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora8.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora9.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora10.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora11.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora12.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora13.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora14.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora15.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora16.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora17.setBackground(java.awt.Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonCancha01ActionPerformed

    private void jButtonCancha02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancha02ActionPerformed
        
        jToggleButtonHora6.setBackground(java.awt.Color.CYAN);
        jToggleButtonHora7.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora8.setBackground(java.awt.Color.MAGENTA);
        jToggleButtonHora9.setBackground(java.awt.Color.ORANGE);
        jToggleButtonHora10.setBackground(java.awt.Color.PINK);
        
        jToggleButtonHora1.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora2.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora3.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora4.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora5.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora11.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora12.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora13.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora14.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora15.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora16.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora17.setBackground(java.awt.Color.LIGHT_GRAY);
        
    }//GEN-LAST:event_jButtonCancha02ActionPerformed

    private void jButtonCancha03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancha03ActionPerformed
        
        jToggleButtonHora11.setBackground(java.awt.Color.RED);
        jToggleButtonHora12.setBackground(java.awt.Color.WHITE);
        jToggleButtonHora13.setBackground(java.awt.Color.YELLOW);
        jToggleButtonHora14.setBackground(java.awt.Color.BLACK);
        jToggleButtonHora15.setBackground(java.awt.Color.CYAN);
        
        jToggleButtonHora1.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora2.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora3.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora4.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora5.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora6.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora7.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora8.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora9.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora10.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora16.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora17.setBackground(java.awt.Color.LIGHT_GRAY);        
        
    }//GEN-LAST:event_jButtonCancha03ActionPerformed

    private void jButtonCancha04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancha04ActionPerformed
        jToggleButtonHora11.setBackground(java.awt.Color.RED);
        jToggleButtonHora12.setBackground(java.awt.Color.WHITE);
        jToggleButtonHora13.setBackground(java.awt.Color.YELLOW);
        jToggleButtonHora14.setBackground(java.awt.Color.BLACK);
        jToggleButtonHora15.setBackground(java.awt.Color.CYAN);
        
        jToggleButtonHora1.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora2.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora3.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora4.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora5.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora6.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora7.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora8.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora9.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora10.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora16.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora17.setBackground(java.awt.Color.LIGHT_GRAY);
        
    }//GEN-LAST:event_jButtonCancha04ActionPerformed

    private void jButtonCancha05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancha05ActionPerformed
        jToggleButtonHora1.setBackground(java.awt.Color.RED);
        jToggleButtonHora2.setBackground(java.awt.Color.BLUE);
        jToggleButtonHora3.setBackground(java.awt.Color.GRAY);
        jToggleButtonHora4.setBackground(java.awt.Color.GREEN);
        jToggleButtonHora5.setBackground(java.awt.Color.DARK_GRAY);
        
        jToggleButtonHora6.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora7.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora8.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora9.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora10.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora11.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora12.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora13.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora14.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora15.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora16.setBackground(java.awt.Color.LIGHT_GRAY);
        jToggleButtonHora17.setBackground(java.awt.Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonCancha05ActionPerformed

    private void jToggleButtonHora1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonHora1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHora1MouseDragged

    private void jToggleButtonHora1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonHora1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHora1MouseClicked

    private void jToggleButtonHora1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonHora1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHora1MouseEntered

    private void jToggleButtonHora1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonHora1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHora1MouseExited

    private void jToggleButtonHora1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonHora1MousePressed

        Point point = evt.getPoint();
        System.out.println("mousePressed at " + point);
  
    }//GEN-LAST:event_jToggleButtonHora1MousePressed

    private void jToggleButtonHora1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonHora1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHora1MouseReleased

    private void jToggleButtonHora1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonHora1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHora1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CV0104v01JDialogReservaCancha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CV0104v01JDialogReservaCancha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CV0104v01JDialogReservaCancha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CV0104v01JDialogReservaCancha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CV0104v01JDialogReservaCancha dialog = new CV0104v01JDialogReservaCancha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupHorario;
    private javax.swing.JButton jButtonCancha01;
    private javax.swing.JButton jButtonCancha02;
    private javax.swing.JButton jButtonCancha03;
    private javax.swing.JButton jButtonCancha04;
    private javax.swing.JButton jButtonCancha05;
    private javax.swing.JButton jButtonCancha06;
    private javax.swing.JButton jButtonCancha08;
    private javax.swing.JButton jButtonCancha09;
    private javax.swing.JButton jButtonCancha10;
    private javax.swing.JButton jButtonCancha11;
    private javax.swing.JButton jButtonCancha12;
    private javax.swing.JButton jButtonCancha13;
    private javax.swing.JButton jButtonCancha14;
    private javax.swing.JButton jButtonCancha15;
    private javax.swing.JButton jButtonCancha16;
    private javax.swing.JButton jButtonCancha17;
    private javax.swing.JButton jButtonCanhca07;
    private javax.swing.JPanel jPanelCancha;
    private javax.swing.JPanel jPanelHorarioPorCancha;
    private javax.swing.JToggleButton jToggleButtonHora1;
    private javax.swing.JToggleButton jToggleButtonHora10;
    private javax.swing.JToggleButton jToggleButtonHora11;
    private javax.swing.JToggleButton jToggleButtonHora12;
    private javax.swing.JToggleButton jToggleButtonHora13;
    private javax.swing.JToggleButton jToggleButtonHora14;
    private javax.swing.JToggleButton jToggleButtonHora15;
    private javax.swing.JToggleButton jToggleButtonHora16;
    private javax.swing.JToggleButton jToggleButtonHora17;
    private javax.swing.JToggleButton jToggleButtonHora18;
    private javax.swing.JToggleButton jToggleButtonHora2;
    private javax.swing.JToggleButton jToggleButtonHora3;
    private javax.swing.JToggleButton jToggleButtonHora4;
    private javax.swing.JToggleButton jToggleButtonHora5;
    private javax.swing.JToggleButton jToggleButtonHora6;
    private javax.swing.JToggleButton jToggleButtonHora7;
    private javax.swing.JToggleButton jToggleButtonHora8;
    private javax.swing.JToggleButton jToggleButtonHora9;
    // End of variables declaration//GEN-END:variables
}
