/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.aemsa.evalua.swing.view.jdialog;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Administrador
 */
public class jDlg0501v01SeleccionRaza extends javax.swing.JDialog {
    String sRutaImagen = "F:\\01NetBeans8.2\\AEMJSEEVL0301v01EvaluacionJava-JDK8\\src\\resources\\imagen\\cap29\\swing\\control\\jradiobottom\\";
    /**
     * Creates new form jDlg0501v01SeleccionRaza
     */
    public jDlg0501v01SeleccionRaza(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBGrpTipoRazaGrupo = new javax.swing.ButtonGroup();
        jPneTitulo = new javax.swing.JPanel();
        jLblTitulo = new javax.swing.JLabel();
        jPneRazaCarne = new javax.swing.JPanel();
        jRBtnShorthorn = new javax.swing.JRadioButton();
        jRBtnHereford = new javax.swing.JRadioButton();
        jRBtnAberdeenAngus = new javax.swing.JRadioButton();
        jRBtnCharollaise = new javax.swing.JRadioButton();
        jRBtnSantaGertrudis = new javax.swing.JRadioButton();
        jRBtnLimousin = new javax.swing.JRadioButton();
        jPneRazaCarneLeche = new javax.swing.JPanel();
        jRBtnNormando = new javax.swing.JRadioButton();
        jRBtnSimmental = new javax.swing.JRadioButton();
        jRBtnBrownSwiss = new javax.swing.JRadioButton();
        jRBtnCriollo = new javax.swing.JRadioButton();
        jRBtnGyr = new javax.swing.JRadioButton();
        jRBtnGuzerat = new javax.swing.JRadioButton();
        jRBtnBrahman = new javax.swing.JRadioButton();
        jPneRazaLeche = new javax.swing.JPanel();
        jRBtnHolstein = new javax.swing.JRadioButton();
        jRBtnJersey = new javax.swing.JRadioButton();
        jBtnImagenRaza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPneTitulo.setBackground(new java.awt.Color(204, 204, 255));

        jLblTitulo.setText("Consulta Razas con Radio Bottom");

        javax.swing.GroupLayout jPneTituloLayout = new javax.swing.GroupLayout(jPneTitulo);
        jPneTitulo.setLayout(jPneTituloLayout);
        jPneTituloLayout.setHorizontalGroup(
            jPneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPneTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPneTituloLayout.setVerticalGroup(
            jPneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPneTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitulo)
                .addContainerGap())
        );

        jPneRazaCarne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBGrpTipoRazaGrupo.add(jRBtnShorthorn);
        jRBtnShorthorn.setText("Shorthorn");
        jRBtnShorthorn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnShorthornMouseClicked(evt);
            }
        });

        jBGrpTipoRazaGrupo.add(jRBtnHereford);
        jRBtnHereford.setText("Hereford");
        jRBtnHereford.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnHerefordMouseClicked(evt);
            }
        });

        jBGrpTipoRazaGrupo.add(jRBtnAberdeenAngus);
        jRBtnAberdeenAngus.setText("Aberdeen Angus");
        jRBtnAberdeenAngus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnAberdeenAngusMouseClicked(evt);
            }
        });

        jBGrpTipoRazaGrupo.add(jRBtnCharollaise);
        jRBtnCharollaise.setText("Charollaise");
        jRBtnCharollaise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnCharollaiseMouseClicked(evt);
            }
        });

        jBGrpTipoRazaGrupo.add(jRBtnSantaGertrudis);
        jRBtnSantaGertrudis.setText("Santa Gertrudis");
        jRBtnSantaGertrudis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnSantaGertrudisMouseClicked(evt);
            }
        });

        jBGrpTipoRazaGrupo.add(jRBtnLimousin);
        jRBtnLimousin.setText("Limousin");
        jRBtnLimousin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnLimousinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPneRazaCarneLayout = new javax.swing.GroupLayout(jPneRazaCarne);
        jPneRazaCarne.setLayout(jPneRazaCarneLayout);
        jPneRazaCarneLayout.setHorizontalGroup(
            jPneRazaCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPneRazaCarneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPneRazaCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBtnShorthorn)
                    .addComponent(jRBtnHereford)
                    .addComponent(jRBtnAberdeenAngus)
                    .addComponent(jRBtnCharollaise)
                    .addComponent(jRBtnSantaGertrudis)
                    .addComponent(jRBtnLimousin))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPneRazaCarneLayout.setVerticalGroup(
            jPneRazaCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPneRazaCarneLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jRBtnShorthorn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBtnHereford)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBtnAberdeenAngus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBtnCharollaise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBtnSantaGertrudis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBtnLimousin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPneRazaCarneLeche.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPneRazaCarneLeche.setPreferredSize(new java.awt.Dimension(149, 228));

        jBGrpTipoRazaGrupo.add(jRBtnNormando);
        jRBtnNormando.setText("Normando");
        jRBtnNormando.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnNormandoMouseClicked(evt);
            }
        });

        jBGrpTipoRazaGrupo.add(jRBtnSimmental);
        jRBtnSimmental.setText("Simmental");
        jRBtnSimmental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnSimmentalMouseClicked(evt);
            }
        });

        jBGrpTipoRazaGrupo.add(jRBtnBrownSwiss);
        jRBtnBrownSwiss.setText("Brown Swiss");
        jRBtnBrownSwiss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnBrownSwissMouseClicked(evt);
            }
        });

        jBGrpTipoRazaGrupo.add(jRBtnCriollo);
        jRBtnCriollo.setText("Criollo");
        jRBtnCriollo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnCriolloMouseClicked(evt);
            }
        });

        jBGrpTipoRazaGrupo.add(jRBtnGyr);
        jRBtnGyr.setText("Gyr");
        jRBtnGyr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnGyrMouseClicked(evt);
            }
        });

        jBGrpTipoRazaGrupo.add(jRBtnGuzerat);
        jRBtnGuzerat.setText("Guzerat");
        jRBtnGuzerat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnGuzeratMouseClicked(evt);
            }
        });

        jBGrpTipoRazaGrupo.add(jRBtnBrahman);
        jRBtnBrahman.setText("Brahman");
        jRBtnBrahman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnBrahmanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPneRazaCarneLecheLayout = new javax.swing.GroupLayout(jPneRazaCarneLeche);
        jPneRazaCarneLeche.setLayout(jPneRazaCarneLecheLayout);
        jPneRazaCarneLecheLayout.setHorizontalGroup(
            jPneRazaCarneLecheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPneRazaCarneLecheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPneRazaCarneLecheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBtnNormando)
                    .addComponent(jRBtnSimmental)
                    .addComponent(jRBtnBrownSwiss)
                    .addComponent(jRBtnCriollo)
                    .addComponent(jRBtnGyr)
                    .addComponent(jRBtnGuzerat)
                    .addComponent(jRBtnBrahman))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPneRazaCarneLecheLayout.setVerticalGroup(
            jPneRazaCarneLecheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPneRazaCarneLecheLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jRBtnNormando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBtnSimmental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBtnBrownSwiss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBtnCriollo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBtnGyr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBtnGuzerat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBtnBrahman)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPneRazaLeche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPneRazaLeche.setPreferredSize(new java.awt.Dimension(149, 228));

        jBGrpTipoRazaGrupo.add(jRBtnHolstein);
        jRBtnHolstein.setText("Holstein");
        jRBtnHolstein.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnHolsteinMouseClicked(evt);
            }
        });

        jBGrpTipoRazaGrupo.add(jRBtnJersey);
        jRBtnJersey.setText("Jersey");
        jRBtnJersey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBtnJerseyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPneRazaLecheLayout = new javax.swing.GroupLayout(jPneRazaLeche);
        jPneRazaLeche.setLayout(jPneRazaLecheLayout);
        jPneRazaLecheLayout.setHorizontalGroup(
            jPneRazaLecheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPneRazaLecheLayout.createSequentialGroup()
                .addGroup(jPneRazaLecheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBtnHolstein)
                    .addComponent(jRBtnJersey))
                .addGap(0, 84, Short.MAX_VALUE))
        );
        jPneRazaLecheLayout.setVerticalGroup(
            jPneRazaLecheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPneRazaLecheLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jRBtnHolstein)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBtnJersey)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPneTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnImagenRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPneRazaCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPneRazaCarneLeche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPneRazaLeche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPneTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPneRazaCarne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPneRazaCarneLeche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPneRazaLeche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnImagenRaza, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBtnShorthornMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnShorthornMouseClicked
        jBtnImagenRaza.setBackground(Color.GREEN);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "ShorthornMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnShorthornMouseClicked

    private void jRBtnHerefordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnHerefordMouseClicked
        jBtnImagenRaza.setBackground(Color.GRAY);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "HerefordMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnHerefordMouseClicked

    private void jRBtnAberdeenAngusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnAberdeenAngusMouseClicked
        jBtnImagenRaza.setBackground(Color.DARK_GRAY);
        
        ImageIcon icon = new ImageIcon(sRutaImagen + "AberdeenAngusMacho" + ".jpg");
        Image img = icon.getImage(); //convertimos icon en una imagen
        Image otraimg = img.getScaledInstance(115,230,java.awt.Image.SCALE_SMOOTH); //creamos una imagen nueva dándole las dimensiones que queramos a la antigua
        ImageIcon otroicon = new ImageIcon(otraimg);
        jBtnImagenRaza.setIcon(otroicon);

    }//GEN-LAST:event_jRBtnAberdeenAngusMouseClicked

    private void jRBtnCharollaiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnCharollaiseMouseClicked
        jBtnImagenRaza.setBackground(Color.CYAN);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "CharolaiseMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnCharollaiseMouseClicked

    private void jRBtnSantaGertrudisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnSantaGertrudisMouseClicked
        jBtnImagenRaza.setBackground(Color.BLUE);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "SantaGertrudisMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnSantaGertrudisMouseClicked

    private void jRBtnLimousinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnLimousinMouseClicked
        jBtnImagenRaza.setBackground(Color.BLACK);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "LimousinMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnLimousinMouseClicked

    private void jRBtnNormandoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnNormandoMouseClicked
        jBtnImagenRaza.setBackground(Color.LIGHT_GRAY);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "NormandoMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnNormandoMouseClicked

    private void jRBtnSimmentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnSimmentalMouseClicked
        jBtnImagenRaza.setBackground(Color.MAGENTA);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "SimmentalMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnSimmentalMouseClicked

    private void jRBtnBrownSwissMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnBrownSwissMouseClicked
        jBtnImagenRaza.setBackground(Color.ORANGE);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "BrownSwissMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnBrownSwissMouseClicked

    private void jRBtnCriolloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnCriolloMouseClicked
        jBtnImagenRaza.setBackground(Color.PINK);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "CriolloMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnCriolloMouseClicked

    private void jRBtnGyrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnGyrMouseClicked
        jBtnImagenRaza.setBackground(Color.RED);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "GyrMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnGyrMouseClicked

    private void jRBtnGuzeratMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnGuzeratMouseClicked
        jBtnImagenRaza.setBackground(Color.WHITE);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "GuzeratMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnGuzeratMouseClicked

    private void jRBtnBrahmanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnBrahmanMouseClicked
        jBtnImagenRaza.setBackground(Color.YELLOW);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "BrahmanMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnBrahmanMouseClicked

    private void jRBtnHolsteinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnHolsteinMouseClicked
        jBtnImagenRaza.setBackground(Color.BLUE);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "HolsteinMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
        
    }//GEN-LAST:event_jRBtnHolsteinMouseClicked

    private void jRBtnJerseyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBtnJerseyMouseClicked
        jBtnImagenRaza.setBackground(Color.cyan);
        ImageIcon oIcono = new ImageIcon(sRutaImagen + "JerseyMacho" + ".jpg");
        jBtnImagenRaza.setIcon(oIcono);
    }//GEN-LAST:event_jRBtnJerseyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDlg0501v01SeleccionRaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDlg0501v01SeleccionRaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDlg0501v01SeleccionRaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDlg0501v01SeleccionRaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDlg0501v01SeleccionRaza dialog = new jDlg0501v01SeleccionRaza(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jBGrpTipoRazaGrupo;
    private javax.swing.JButton jBtnImagenRaza;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JPanel jPneRazaCarne;
    private javax.swing.JPanel jPneRazaCarneLeche;
    private javax.swing.JPanel jPneRazaLeche;
    private javax.swing.JPanel jPneTitulo;
    private javax.swing.JRadioButton jRBtnAberdeenAngus;
    private javax.swing.JRadioButton jRBtnBrahman;
    private javax.swing.JRadioButton jRBtnBrownSwiss;
    private javax.swing.JRadioButton jRBtnCharollaise;
    private javax.swing.JRadioButton jRBtnCriollo;
    private javax.swing.JRadioButton jRBtnGuzerat;
    private javax.swing.JRadioButton jRBtnGyr;
    private javax.swing.JRadioButton jRBtnHereford;
    private javax.swing.JRadioButton jRBtnHolstein;
    private javax.swing.JRadioButton jRBtnJersey;
    private javax.swing.JRadioButton jRBtnLimousin;
    private javax.swing.JRadioButton jRBtnNormando;
    private javax.swing.JRadioButton jRBtnSantaGertrudis;
    private javax.swing.JRadioButton jRBtnShorthorn;
    private javax.swing.JRadioButton jRBtnSimmental;
    // End of variables declaration//GEN-END:variables
}
