/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.aemsa.cap29.swing;

public class CV0203v01JDialogRegistroNotasUniversitario extends javax.swing.JDialog {

    /**
     * Creates new form JD01v01RegistroNotasUniversitario
     */
    public CV0203v01JDialogRegistroNotasUniversitario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jPnlDatosGenerales = new javax.swing.JPanel();
        jLblNroDni = new javax.swing.JLabel();
        jTxtFNroDni = new javax.swing.JTextField();
        jLblNroCarnetUniversitario = new javax.swing.JLabel();
        jTxtFNroCarnetUniversitario = new javax.swing.JTextField();
        jLblFacultad = new javax.swing.JLabel();
        jLblEscuela = new javax.swing.JLabel();
        jTxtFFacultad = new javax.swing.JTextField();
        jTxtFEscuela = new javax.swing.JTextField();
        jLblApellidoNombre = new javax.swing.JLabel();
        jTxtFApellidoNombre = new javax.swing.JTextField();
        jBtnBuscarAlumno = new javax.swing.JButton();
        jLblCurso = new javax.swing.JLabel();
        jCboCurso = new javax.swing.JComboBox();
        jPnlUnidadOperativa1 = new javax.swing.JPanel();
        jTxtFNotaLectura1 = new javax.swing.JTextField();
        jTxtFNotaExamenOral1 = new javax.swing.JTextField();
        jLblNotaLecturaUO1 = new javax.swing.JLabel();
        jLblNotaExamenOralUO1 = new javax.swing.JLabel();
        jLblNotaExamenParcialUO1 = new javax.swing.JLabel();
        jLblPromedioUO1 = new javax.swing.JLabel();
        jTxtFNotaExamenParcial1 = new javax.swing.JTextField();
        jTxtFNotaPromedioUO1 = new javax.swing.JTextField();
        jPnlPoliticaEvaluacion1 = new javax.swing.JPanel();
        jRbtnPoliticaA1 = new javax.swing.JRadioButton();
        jRbtnPoliticaB1 = new javax.swing.JRadioButton();
        jTxtFPoliticaTipoA1 = new javax.swing.JTextField();
        jTxtFPoliticaTipoB1 = new javax.swing.JTextField();
        jPnlUnidadOperatica2 = new javax.swing.JPanel();
        jTxtFNotaLectura2 = new javax.swing.JTextField();
        jTxtFNotaExamenOral2 = new javax.swing.JTextField();
        jLblNotaLectura2 = new javax.swing.JLabel();
        jLblNotaExamenOral2 = new javax.swing.JLabel();
        jLblNotaExamenParcial2 = new javax.swing.JLabel();
        jLblPromedioUO2 = new javax.swing.JLabel();
        jTxtFNotaExamenParcial2 = new javax.swing.JTextField();
        jTxtFNotaPromedioUO2 = new javax.swing.JTextField();
        jPnlResumenPromedio = new javax.swing.JPanel();
        jTxtFNotaTrabajo1 = new javax.swing.JTextField();
        jTxtFNotaTrabajo2 = new javax.swing.JTextField();
        jLblDescripcionUO = new javax.swing.JLabel();
        jLblNotaTrabajo2 = new javax.swing.JLabel();
        jLblUnidadOperativa1 = new javax.swing.JLabel();
        jLblUnidadOperativa2 = new javax.swing.JLabel();
        jTxtFNotaTrabajo3 = new javax.swing.JTextField();
        jTxtFFactor1 = new javax.swing.JTextField();
        jLblUnidadOperativa3 = new javax.swing.JLabel();
        jLblFactor = new javax.swing.JLabel();
        jTxtFFactor2 = new javax.swing.JTextField();
        jTxtFFactor3 = new javax.swing.JTextField();
        jLblValorFactor = new javax.swing.JLabel();
        jTxtFValorFactor1 = new javax.swing.JTextField();
        jTxtFValorFactor2 = new javax.swing.JTextField();
        jTxtFValorFactor3 = new javax.swing.JTextField();
        jLblSumaFactores = new javax.swing.JLabel();
        jTxtFSumaValorFactor = new javax.swing.JTextField();
        jLblPromedioFinalNumeros = new javax.swing.JLabel();
        jTxtFPromedioFinalNumeros = new javax.swing.JTextField();
        jLblPromedioFinalLetras = new javax.swing.JLabel();
        jTxtFPromedioFinalLetras = new javax.swing.JTextField();
        jPnlTrabajosInvestigacion = new javax.swing.JPanel();
        jTxtFNotaTrabajo4 = new javax.swing.JTextField();
        jTxtFNotaTrabajo5 = new javax.swing.JTextField();
        jLblNotaTrabajo4 = new javax.swing.JLabel();
        jLblNotaTrabajo5 = new javax.swing.JLabel();
        jLblNotaTrabajo6 = new javax.swing.JLabel();
        jLblPromedioTrabajos1 = new javax.swing.JLabel();
        jTxtFNotaTrabajo6 = new javax.swing.JTextField();
        jTxtFPromedioTrabajos1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Notas de los Alumnos");
        setBackground(new java.awt.Color(51, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 0, 255));
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setLabelFor(jLTitulo);
        jLTitulo.setText("Registro de Notas de Alumnos");
        jLTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLTitulo.setName(""); // NOI18N

        jPnlDatosGenerales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Generales", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPnlDatosGenerales.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLblNroDni.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblNroDni.setText("N° DNI");

        jTxtFNroDni.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNroDni.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNroDni.setText("09313658");

        jLblNroCarnetUniversitario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblNroCarnetUniversitario.setText("N° Carnet Universitario");

        jTxtFNroCarnetUniversitario.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNroCarnetUniversitario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNroCarnetUniversitario.setText("20130101099999");

        jLblFacultad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblFacultad.setText("Facultad");

        jLblEscuela.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblEscuela.setText("Escuela");

        jTxtFFacultad.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFFacultad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFFacultad.setText("CIENCIAS");
        jTxtFFacultad.setEnabled(false);

        jTxtFEscuela.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFEscuela.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFEscuela.setText("ESTADISTICA E INFORMATICA");
        jTxtFEscuela.setEnabled(false);

        jLblApellidoNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblApellidoNombre.setText("Apellidos y Nombres");

        jTxtFApellidoNombre.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFApellidoNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFApellidoNombre.setText("DIAZ CARDENAS ESTEBAN ALEXANDER");
        jTxtFApellidoNombre.setEnabled(false);

        jBtnBuscarAlumno.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnBuscarAlumno.setText(".....");
        jBtnBuscarAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLblCurso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblCurso.setText("Curso");

        jCboCurso.setBackground(new java.awt.Color(255, 255, 204));
        jCboCurso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jCboCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fundamentos de Programacion", "Matematica Basica I", "Economia", "Actividades I" }));

        javax.swing.GroupLayout jPnlDatosGeneralesLayout = new javax.swing.GroupLayout(jPnlDatosGenerales);
        jPnlDatosGenerales.setLayout(jPnlDatosGeneralesLayout);
        jPnlDatosGeneralesLayout.setHorizontalGroup(
            jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosGeneralesLayout.createSequentialGroup()
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnlDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(jLblFacultad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblEscuela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFEscuela))
                    .addGroup(jPnlDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(jLblNroDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtFNroDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblNroCarnetUniversitario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtFNroCarnetUniversitario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
            .addGroup(jPnlDatosGeneralesLayout.createSequentialGroup()
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblApellidoNombre)
                    .addComponent(jLblCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtFApellidoNombre)
                    .addComponent(jCboCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnBuscarAlumno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlDatosGeneralesLayout.setVerticalGroup(
            jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNroDni)
                    .addComponent(jTxtFNroDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNroCarnetUniversitario)
                    .addComponent(jTxtFNroCarnetUniversitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblFacultad)
                        .addComponent(jTxtFFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblEscuela)
                        .addComponent(jTxtFEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblApellidoNombre)
                    .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtFApellidoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnBuscarAlumno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCurso))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPnlUnidadOperativa1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unidad Operativa N° 1", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPnlUnidadOperativa1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jTxtFNotaLectura1.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNotaLectura1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaLectura1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaLectura1.setText("09");

        jTxtFNotaExamenOral1.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNotaExamenOral1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaExamenOral1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaExamenOral1.setText("15");

        jLblNotaLecturaUO1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblNotaLecturaUO1.setText("Lecturas o prácticas");

        jLblNotaExamenOralUO1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblNotaExamenOralUO1.setText("Examen Oral");

        jLblNotaExamenParcialUO1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblNotaExamenParcialUO1.setText("Examen Parcial");

        jLblPromedioUO1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblPromedioUO1.setText("Promedio U.O");

        jTxtFNotaExamenParcial1.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNotaExamenParcial1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaExamenParcial1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaExamenParcial1.setText("15");

        jTxtFNotaPromedioUO1.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFNotaPromedioUO1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaPromedioUO1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaPromedioUO1.setText("15");
        jTxtFNotaPromedioUO1.setEnabled(false);

        javax.swing.GroupLayout jPnlUnidadOperativa1Layout = new javax.swing.GroupLayout(jPnlUnidadOperativa1);
        jPnlUnidadOperativa1.setLayout(jPnlUnidadOperativa1Layout);
        jPnlUnidadOperativa1Layout.setHorizontalGroup(
            jPnlUnidadOperativa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUnidadOperativa1Layout.createSequentialGroup()
                .addGroup(jPnlUnidadOperativa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblNotaExamenParcialUO1)
                    .addComponent(jLblNotaExamenOralUO1)
                    .addComponent(jLblNotaLecturaUO1)
                    .addComponent(jLblPromedioUO1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlUnidadOperativa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtFNotaLectura1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jTxtFNotaExamenOral1)
                    .addComponent(jTxtFNotaExamenParcial1)
                    .addComponent(jTxtFNotaPromedioUO1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPnlUnidadOperativa1Layout.setVerticalGroup(
            jPnlUnidadOperativa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUnidadOperativa1Layout.createSequentialGroup()
                .addGroup(jPnlUnidadOperativa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFNotaLectura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNotaLecturaUO1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlUnidadOperativa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNotaExamenOralUO1)
                    .addComponent(jTxtFNotaExamenOral1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlUnidadOperativa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNotaExamenParcialUO1)
                    .addComponent(jTxtFNotaExamenParcial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlUnidadOperativa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPromedioUO1)
                    .addComponent(jTxtFNotaPromedioUO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnlPoliticaEvaluacion1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Política de Evaluación", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPnlPoliticaEvaluacion1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jRbtnPoliticaA1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jRbtnPoliticaA1.setText("Tipo B al promedio");

        jRbtnPoliticaB1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jRbtnPoliticaB1.setSelected(true);
        jRbtnPoliticaB1.setText("Tipo A al promedio");
        jRbtnPoliticaB1.setToolTipText("");

        jTxtFPoliticaTipoA1.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFPoliticaTipoA1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFPoliticaTipoA1.setText("35%, 35%, 30%");
        jTxtFPoliticaTipoA1.setEnabled(false);

        jTxtFPoliticaTipoB1.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFPoliticaTipoB1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFPoliticaTipoB1.setText("30%, 30%, 40%");
        jTxtFPoliticaTipoB1.setEnabled(false);

        javax.swing.GroupLayout jPnlPoliticaEvaluacion1Layout = new javax.swing.GroupLayout(jPnlPoliticaEvaluacion1);
        jPnlPoliticaEvaluacion1.setLayout(jPnlPoliticaEvaluacion1Layout);
        jPnlPoliticaEvaluacion1Layout.setHorizontalGroup(
            jPnlPoliticaEvaluacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPoliticaEvaluacion1Layout.createSequentialGroup()
                .addGroup(jPnlPoliticaEvaluacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRbtnPoliticaB1)
                    .addComponent(jRbtnPoliticaA1)
                    .addGroup(jPnlPoliticaEvaluacion1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPnlPoliticaEvaluacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFPoliticaTipoA1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFPoliticaTipoB1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlPoliticaEvaluacion1Layout.setVerticalGroup(
            jPnlPoliticaEvaluacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPoliticaEvaluacion1Layout.createSequentialGroup()
                .addComponent(jRbtnPoliticaB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtFPoliticaTipoA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRbtnPoliticaA1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtFPoliticaTipoB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnlUnidadOperatica2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unidad Operativa N° 2", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPnlUnidadOperatica2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jTxtFNotaLectura2.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNotaLectura2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaLectura2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaLectura2.setText("09");

        jTxtFNotaExamenOral2.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNotaExamenOral2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaExamenOral2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaExamenOral2.setText("15");

        jLblNotaLectura2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblNotaLectura2.setText("Lecturas o prácticas");

        jLblNotaExamenOral2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblNotaExamenOral2.setText("Examen Oral");

        jLblNotaExamenParcial2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblNotaExamenParcial2.setText("Examen Parcial");

        jLblPromedioUO2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblPromedioUO2.setText("Promedio U.O");

        jTxtFNotaExamenParcial2.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNotaExamenParcial2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaExamenParcial2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaExamenParcial2.setText("15");

        jTxtFNotaPromedioUO2.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFNotaPromedioUO2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaPromedioUO2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaPromedioUO2.setText("15");
        jTxtFNotaPromedioUO2.setEnabled(false);

        javax.swing.GroupLayout jPnlUnidadOperatica2Layout = new javax.swing.GroupLayout(jPnlUnidadOperatica2);
        jPnlUnidadOperatica2.setLayout(jPnlUnidadOperatica2Layout);
        jPnlUnidadOperatica2Layout.setHorizontalGroup(
            jPnlUnidadOperatica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUnidadOperatica2Layout.createSequentialGroup()
                .addGroup(jPnlUnidadOperatica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblNotaExamenParcial2)
                    .addComponent(jLblNotaExamenOral2)
                    .addComponent(jLblNotaLectura2)
                    .addComponent(jLblPromedioUO2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlUnidadOperatica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtFNotaLectura2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jTxtFNotaExamenOral2)
                    .addComponent(jTxtFNotaExamenParcial2)
                    .addComponent(jTxtFNotaPromedioUO2))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPnlUnidadOperatica2Layout.setVerticalGroup(
            jPnlUnidadOperatica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUnidadOperatica2Layout.createSequentialGroup()
                .addGroup(jPnlUnidadOperatica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFNotaLectura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNotaLectura2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlUnidadOperatica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNotaExamenOral2)
                    .addComponent(jTxtFNotaExamenOral2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlUnidadOperatica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNotaExamenParcial2)
                    .addComponent(jTxtFNotaExamenParcial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlUnidadOperatica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPromedioUO2)
                    .addComponent(jTxtFNotaPromedioUO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnlResumenPromedio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen Informativo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPnlResumenPromedio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jTxtFNotaTrabajo1.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNotaTrabajo1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaTrabajo1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaTrabajo1.setText("09");

        jTxtFNotaTrabajo2.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNotaTrabajo2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaTrabajo2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaTrabajo2.setText("15");

        jLblDescripcionUO.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblDescripcionUO.setText("Descripción");

        jLblNotaTrabajo2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblNotaTrabajo2.setText("Promedio");

        jLblUnidadOperativa1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblUnidadOperativa1.setText("Unidad Operativa N° 01");

        jLblUnidadOperativa2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblUnidadOperativa2.setText("Unidad Operativa N° 02");

        jTxtFNotaTrabajo3.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNotaTrabajo3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaTrabajo3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaTrabajo3.setText("15");

        jTxtFFactor1.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFFactor1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFFactor1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFFactor1.setText("35%");
        jTxtFFactor1.setEnabled(false);

        jLblUnidadOperativa3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblUnidadOperativa3.setText("Trabajo Investigación");

        jLblFactor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblFactor.setText("Factor");

        jTxtFFactor2.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFFactor2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFFactor2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFFactor2.setText("35%");
        jTxtFFactor2.setEnabled(false);

        jTxtFFactor3.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFFactor3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFFactor3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFFactor3.setText("30%");
        jTxtFFactor3.setEnabled(false);

        jLblValorFactor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblValorFactor.setText("Valor del factor");

        jTxtFValorFactor1.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFValorFactor1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFValorFactor1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFValorFactor1.setText("3.1");
        jTxtFValorFactor1.setEnabled(false);

        jTxtFValorFactor2.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFValorFactor2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFValorFactor2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFValorFactor2.setText("5.2");
        jTxtFValorFactor2.setEnabled(false);

        jTxtFValorFactor3.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFValorFactor3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFValorFactor3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFValorFactor3.setText("4.0");
        jTxtFValorFactor3.setEnabled(false);

        jLblSumaFactores.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblSumaFactores.setText("Suma valor factor");

        jTxtFSumaValorFactor.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFSumaValorFactor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFSumaValorFactor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFSumaValorFactor.setText("12.3");
        jTxtFSumaValorFactor.setEnabled(false);

        jLblPromedioFinalNumeros.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblPromedioFinalNumeros.setText("Promedio final en números");

        jTxtFPromedioFinalNumeros.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFPromedioFinalNumeros.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFPromedioFinalNumeros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFPromedioFinalNumeros.setText("12");
        jTxtFPromedioFinalNumeros.setEnabled(false);

        jLblPromedioFinalLetras.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblPromedioFinalLetras.setText("Promedio final en letras");

        jTxtFPromedioFinalLetras.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFPromedioFinalLetras.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFPromedioFinalLetras.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtFPromedioFinalLetras.setText("DOCE");
        jTxtFPromedioFinalLetras.setEnabled(false);

        javax.swing.GroupLayout jPnlResumenPromedioLayout = new javax.swing.GroupLayout(jPnlResumenPromedio);
        jPnlResumenPromedio.setLayout(jPnlResumenPromedioLayout);
        jPnlResumenPromedioLayout.setHorizontalGroup(
            jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlResumenPromedioLayout.createSequentialGroup()
                .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPnlResumenPromedioLayout.createSequentialGroup()
                            .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLblUnidadOperativa1)
                                .addComponent(jLblDescripcionUO)
                                .addComponent(jLblUnidadOperativa2)
                                .addComponent(jLblUnidadOperativa3))
                            .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPnlResumenPromedioLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtFNotaTrabajo1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtFNotaTrabajo2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtFNotaTrabajo3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPnlResumenPromedioLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLblNotaTrabajo2)))
                            .addGap(20, 20, 20)
                            .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPnlResumenPromedioLayout.createSequentialGroup()
                                    .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtFFactor1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtFFactor2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtFFactor3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(42, 42, 42)
                                    .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtFValorFactor1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtFValorFactor2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtFValorFactor3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtFSumaValorFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtFPromedioFinalNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPnlResumenPromedioLayout.createSequentialGroup()
                                    .addComponent(jLblFactor)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtFPromedioFinalLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLblValorFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPnlResumenPromedioLayout.createSequentialGroup()
                            .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblSumaFactores, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblPromedioFinalLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(169, 169, 169)))
                    .addGroup(jPnlResumenPromedioLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLblPromedioFinalNumeros)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlResumenPromedioLayout.setVerticalGroup(
            jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlResumenPromedioLayout.createSequentialGroup()
                .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDescripcionUO)
                    .addComponent(jLblNotaTrabajo2)
                    .addComponent(jLblFactor)
                    .addComponent(jLblValorFactor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlResumenPromedioLayout.createSequentialGroup()
                        .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtFNotaTrabajo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblUnidadOperativa1)
                            .addComponent(jTxtFFactor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblUnidadOperativa2)
                            .addComponent(jTxtFNotaTrabajo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFFactor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblUnidadOperativa3)
                            .addComponent(jTxtFNotaTrabajo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFFactor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnlResumenPromedioLayout.createSequentialGroup()
                        .addComponent(jTxtFValorFactor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFValorFactor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtFValorFactor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblSumaFactores)
                    .addComponent(jTxtFSumaValorFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPromedioFinalNumeros)
                    .addComponent(jTxtFPromedioFinalNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlResumenPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPromedioFinalLetras)
                    .addComponent(jTxtFPromedioFinalLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPnlTrabajosInvestigacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trabajos de Investigación", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPnlTrabajosInvestigacion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jTxtFNotaTrabajo4.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNotaTrabajo4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaTrabajo4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaTrabajo4.setText("09");

        jTxtFNotaTrabajo5.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNotaTrabajo5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaTrabajo5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaTrabajo5.setText("15");

        jLblNotaTrabajo4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblNotaTrabajo4.setText("Trabajo N° 01");

        jLblNotaTrabajo5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblNotaTrabajo5.setText("Trabajo N° 02");

        jLblNotaTrabajo6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblNotaTrabajo6.setText("Trabajo N° 03");

        jLblPromedioTrabajos1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLblPromedioTrabajos1.setText("Promedio Trabajos");

        jTxtFNotaTrabajo6.setBackground(new java.awt.Color(204, 255, 153));
        jTxtFNotaTrabajo6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFNotaTrabajo6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFNotaTrabajo6.setText("15");

        jTxtFPromedioTrabajos1.setBackground(new java.awt.Color(255, 255, 204));
        jTxtFPromedioTrabajos1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTxtFPromedioTrabajos1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtFPromedioTrabajos1.setText("15");
        jTxtFPromedioTrabajos1.setEnabled(false);

        javax.swing.GroupLayout jPnlTrabajosInvestigacionLayout = new javax.swing.GroupLayout(jPnlTrabajosInvestigacion);
        jPnlTrabajosInvestigacion.setLayout(jPnlTrabajosInvestigacionLayout);
        jPnlTrabajosInvestigacionLayout.setHorizontalGroup(
            jPnlTrabajosInvestigacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTrabajosInvestigacionLayout.createSequentialGroup()
                .addGroup(jPnlTrabajosInvestigacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblNotaTrabajo6)
                    .addComponent(jLblNotaTrabajo5)
                    .addComponent(jLblNotaTrabajo4)
                    .addComponent(jLblPromedioTrabajos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPnlTrabajosInvestigacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtFNotaTrabajo4)
                    .addComponent(jTxtFNotaTrabajo5)
                    .addComponent(jTxtFNotaTrabajo6)
                    .addComponent(jTxtFPromedioTrabajos1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPnlTrabajosInvestigacionLayout.setVerticalGroup(
            jPnlTrabajosInvestigacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTrabajosInvestigacionLayout.createSequentialGroup()
                .addGroup(jPnlTrabajosInvestigacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFNotaTrabajo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNotaTrabajo4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlTrabajosInvestigacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNotaTrabajo5)
                    .addComponent(jTxtFNotaTrabajo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlTrabajosInvestigacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNotaTrabajo6)
                    .addComponent(jTxtFNotaTrabajo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlTrabajosInvestigacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPromedioTrabajos1)
                    .addComponent(jTxtFPromedioTrabajos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPnlDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPnlPoliticaEvaluacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPnlUnidadOperativa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(222, 222, 222))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPnlUnidadOperatica2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addComponent(jPnlTrabajosInvestigacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jPnlResumenPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTitulo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPnlPoliticaEvaluacion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPnlDatosGenerales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPnlUnidadOperativa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPnlUnidadOperatica2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPnlTrabajosInvestigacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlResumenPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CV0203v01JDialogRegistroNotasUniversitario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CV0203v01JDialogRegistroNotasUniversitario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CV0203v01JDialogRegistroNotasUniversitario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CV0203v01JDialogRegistroNotasUniversitario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CV0203v01JDialogRegistroNotasUniversitario dialog = new CV0203v01JDialogRegistroNotasUniversitario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarAlumno;
    private javax.swing.JComboBox jCboCurso;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLblApellidoNombre;
    private javax.swing.JLabel jLblCurso;
    private javax.swing.JLabel jLblDescripcionUO;
    private javax.swing.JLabel jLblEscuela;
    private javax.swing.JLabel jLblFactor;
    private javax.swing.JLabel jLblFacultad;
    private javax.swing.JLabel jLblNotaExamenOral2;
    private javax.swing.JLabel jLblNotaExamenOralUO1;
    private javax.swing.JLabel jLblNotaExamenParcial2;
    private javax.swing.JLabel jLblNotaExamenParcialUO1;
    private javax.swing.JLabel jLblNotaLectura2;
    private javax.swing.JLabel jLblNotaLecturaUO1;
    private javax.swing.JLabel jLblNotaTrabajo2;
    private javax.swing.JLabel jLblNotaTrabajo4;
    private javax.swing.JLabel jLblNotaTrabajo5;
    private javax.swing.JLabel jLblNotaTrabajo6;
    private javax.swing.JLabel jLblNroCarnetUniversitario;
    private javax.swing.JLabel jLblNroDni;
    private javax.swing.JLabel jLblPromedioFinalLetras;
    private javax.swing.JLabel jLblPromedioFinalNumeros;
    private javax.swing.JLabel jLblPromedioTrabajos1;
    private javax.swing.JLabel jLblPromedioUO1;
    private javax.swing.JLabel jLblPromedioUO2;
    private javax.swing.JLabel jLblSumaFactores;
    private javax.swing.JLabel jLblUnidadOperativa1;
    private javax.swing.JLabel jLblUnidadOperativa2;
    private javax.swing.JLabel jLblUnidadOperativa3;
    private javax.swing.JLabel jLblValorFactor;
    private javax.swing.JPanel jPnlDatosGenerales;
    private javax.swing.JPanel jPnlPoliticaEvaluacion1;
    private javax.swing.JPanel jPnlResumenPromedio;
    private javax.swing.JPanel jPnlTrabajosInvestigacion;
    private javax.swing.JPanel jPnlUnidadOperatica2;
    private javax.swing.JPanel jPnlUnidadOperativa1;
    private javax.swing.JRadioButton jRbtnPoliticaA1;
    private javax.swing.JRadioButton jRbtnPoliticaB1;
    private javax.swing.JTextField jTxtFApellidoNombre;
    private javax.swing.JTextField jTxtFEscuela;
    private javax.swing.JTextField jTxtFFactor1;
    private javax.swing.JTextField jTxtFFactor2;
    private javax.swing.JTextField jTxtFFactor3;
    private javax.swing.JTextField jTxtFFacultad;
    private javax.swing.JTextField jTxtFNotaExamenOral1;
    private javax.swing.JTextField jTxtFNotaExamenOral2;
    private javax.swing.JTextField jTxtFNotaExamenParcial1;
    private javax.swing.JTextField jTxtFNotaExamenParcial2;
    private javax.swing.JTextField jTxtFNotaLectura1;
    private javax.swing.JTextField jTxtFNotaLectura2;
    private javax.swing.JTextField jTxtFNotaPromedioUO1;
    private javax.swing.JTextField jTxtFNotaPromedioUO2;
    private javax.swing.JTextField jTxtFNotaTrabajo1;
    private javax.swing.JTextField jTxtFNotaTrabajo2;
    private javax.swing.JTextField jTxtFNotaTrabajo3;
    private javax.swing.JTextField jTxtFNotaTrabajo4;
    private javax.swing.JTextField jTxtFNotaTrabajo5;
    private javax.swing.JTextField jTxtFNotaTrabajo6;
    private javax.swing.JTextField jTxtFNroCarnetUniversitario;
    private javax.swing.JTextField jTxtFNroDni;
    private javax.swing.JTextField jTxtFPoliticaTipoA1;
    private javax.swing.JTextField jTxtFPoliticaTipoB1;
    private javax.swing.JTextField jTxtFPromedioFinalLetras;
    private javax.swing.JTextField jTxtFPromedioFinalNumeros;
    private javax.swing.JTextField jTxtFPromedioTrabajos1;
    private javax.swing.JTextField jTxtFSumaValorFactor;
    private javax.swing.JTextField jTxtFValorFactor1;
    private javax.swing.JTextField jTxtFValorFactor2;
    private javax.swing.JTextField jTxtFValorFactor3;
    // End of variables declaration//GEN-END:variables
}
