/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.aemsa.cap29.swing.controls07.combobox;

import java.util.ArrayList;
import javax.swing.JComboBox;
import pe.aemsa.cap29.swing.controls07.combobox.entidad.CEAnimal;
import pe.aemsa.cap29.swing.controls07.combobox.impl.CM0701v01ArrayListComboBoxModel;
import pe.aemsa.cap29.swing.controls07.combobox.modelo.CDDatosParaCombo;

/**
 *
 * @author user
 */
public class JDlg0702v01ComboAnimalesMetodoComboBoxModel extends javax.swing.JDialog {
    private CDDatosParaCombo oCDDatoCombo;
    private ArrayList<CEAnimal> oListaAnimal;
    private CEAnimal oCEAnimal;
    /**
     * Creates new form JDlg0702v01ComboAnimalesComboBoxModel
     */
    public JDlg0702v01ComboAnimalesMetodoComboBoxModel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // 2. Combo por medio de ComboBoxModel de un modelo
        oListaAnimal = new ArrayList<>();
        traerAnimal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblComboAnimales = new javax.swing.JLabel();
        jCbxModeloAnimal = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblComboAnimales.setText("1. Combo con ComboBoxModel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLblComboAnimales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCbxModeloAnimal, 0, 213, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblComboAnimales)
                    .addComponent(jCbxModeloAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg0702v01ComboAnimalesMetodoComboBoxModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg0702v01ComboAnimalesMetodoComboBoxModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg0702v01ComboAnimalesMetodoComboBoxModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg0702v01ComboAnimalesMetodoComboBoxModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg0702v01ComboAnimalesMetodoComboBoxModel dialog = new JDlg0702v01ComboAnimalesMetodoComboBoxModel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void traerAnimal(){
        oCDDatoCombo = new CDDatosParaCombo();
        ArrayList<CEAnimal> oResultadoListaAnimales = oCDDatoCombo.dataVacas();
        if (oResultadoListaAnimales != null){
            llenarModeloCombo(jCbxModeloAnimal, oResultadoListaAnimales);
            int iTamano = oResultadoListaAnimales.size();

            for (int i=0; i < iTamano; i++){
                oCEAnimal = new CEAnimal();                
                oCEAnimal = (CEAnimal) oResultadoListaAnimales.get(i);
                oListaAnimal.add(oCEAnimal);
            }
        }
    }

    private void llenarModeloCombo(JComboBox<CEAnimal> poJCbx, ArrayList<CEAnimal> poLista){
        CM0701v01ArrayListComboBoxModel oModeloCombo = new CM0701v01ArrayListComboBoxModel(poLista);
        poJCbx.setModel(oModeloCombo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCbxModeloAnimal;
    private javax.swing.JLabel jLblComboAnimales;
    // End of variables declaration//GEN-END:variables
}
