/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.aemsa.cap29.swing.controls07.combobox;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import pe.aemsa.cap29.swing.controls07.combobox.entidad.CEAnimal;
import pe.aemsa.cap29.swing.controls07.combobox.modelo.CDDataDemo;

/**
 *
 * @author ALDV
 */
public class JDlg0701v01ComboAnimalesMetodoSimple extends javax.swing.JDialog {
        private ArrayList<CEAnimal> moLista;
        private CEAnimal moCEAnimal;
    /**
     * Creates new form JDlg0701v01ComboAnimales
     */
    public JDlg0701v01ComboAnimalesMetodoSimple(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // 1. Combo Declarado en las propiedades setModel
        
        // 2. Combo String de Animales
        jCbxListaAnimales.addItem("..... [Seleccione] .....");
        jCbxListaAnimales.addItem("Pasquel");
        jCbxListaAnimales.addItem("Raquel");
        jCbxListaAnimales.addItem("Marco");
        
        // 3. Combo cargado de una lista
        // Al declarar el JComboBox se debe dejar en blanco la propiedad Type Parameters
        cargaComboAnimal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCbxListaAnimales = new javax.swing.JComboBox<>();
        jLblComboAnimales = new javax.swing.JLabel();
        JLblComboModelo = new javax.swing.JLabel();
        jCbxModeloAnimal = new javax.swing.JComboBox<>();
        JCbxComboListaAnimal = new javax.swing.JComboBox();
        JLblComboAnimalLista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCbxListaAnimales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLblComboAnimales.setText("2. Carga combo en propiedad addItem de JComboBox");

        JLblComboModelo.setText("1. Carga combo asignando en propiedad model en diseno ");

        jCbxModeloAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacas", "Toros", "Bueyes" }));

        JCbxComboListaAnimal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JLblComboAnimalLista.setText("3. Carga combo utilizando un ArrayList");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLblComboModelo)
                    .addComponent(jLblComboAnimales)
                    .addComponent(JLblComboAnimalLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCbxModeloAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JCbxComboListaAnimal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCbxListaAnimales, javax.swing.GroupLayout.Alignment.LEADING, 0, 143, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblComboModelo)
                    .addComponent(jCbxModeloAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblComboAnimales)
                    .addComponent(jCbxListaAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCbxComboListaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLblComboAnimalLista))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg0701v01ComboAnimalesMetodoSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg0701v01ComboAnimalesMetodoSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg0701v01ComboAnimalesMetodoSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg0701v01ComboAnimalesMetodoSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg0701v01ComboAnimalesMetodoSimple dialog = new JDlg0701v01ComboAnimalesMetodoSimple(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void cargaComboAnimal(){
        moLista = new ArrayList<>();
        moCEAnimal = new CEAnimal();
        CDDataDemo oData = new CDDataDemo();
        
        JCbxComboListaAnimal.removeAllItems();
        moLista = oData.dataVacas();
        if (moLista != null){
             for (int i=0; i<moLista.size(); i++){
                 moCEAnimal = moLista.get(i);
                 JCbxComboListaAnimal.addItem(moCEAnimal);
             }
        }else{
            JOptionPane.showMessageDialog(this, "Lista Vacia");
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JCbxComboListaAnimal;
    private javax.swing.JLabel JLblComboAnimalLista;
    private javax.swing.JLabel JLblComboModelo;
    private javax.swing.JComboBox<String> jCbxListaAnimales;
    private javax.swing.JComboBox<String> jCbxModeloAnimal;
    private javax.swing.JLabel jLblComboAnimales;
    // End of variables declaration//GEN-END:variables
}
