package pe.aemsa.evalua.swing.view.jbutton;

import java.awt.Container;

public class jDlg0101v01MostrarBotonesHorario extends javax.swing.JDialog {

    public jDlg0101v01MostrarBotonesHorario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Container container = getContentPane();
        container.setLayout(null);
        
        String asHoraAlquiler[][] = new String[9][3];
        
        asHoraAlquiler[1][1] = "  6 -   7 am";
        asHoraAlquiler[2][1] = "  8 -   9 am";
        asHoraAlquiler[3][1] = "10 - 11 am";
        asHoraAlquiler[4][1] = "12 - 13 pm";
        asHoraAlquiler[5][1] = "14 - 15 pm";
        asHoraAlquiler[6][1] = "16 - 17 pm";
        asHoraAlquiler[7][1] = "18 - 19 pm";
        asHoraAlquiler[8][1] = "20 - 21 pm";

        asHoraAlquiler[1][2] = "  7 -   8 am";
        asHoraAlquiler[2][2] = "  9 - 10 am";
        asHoraAlquiler[3][2] = "11 - 12 am";
        asHoraAlquiler[4][2] = "13 - 14 pm";
        asHoraAlquiler[5][2] = "15 - 16 pm";
        asHoraAlquiler[6][2] = "17 - 18 pm";
        asHoraAlquiler[7][2] = "19 - 20 pm";
        asHoraAlquiler[8][2] = "21 - 22 pm";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDlg0101v01MostrarBotonesHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDlg0101v01MostrarBotonesHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDlg0101v01MostrarBotonesHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDlg0101v01MostrarBotonesHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDlg0101v01MostrarBotonesHorario dialog = new jDlg0101v01MostrarBotonesHorario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
