/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aemsa.vista.colecciones.set;

import aemsa.entidad.colecciones.CE0201v01RangoImporte;
import aemsa.modelo.CD0201v01DataRangoImporte;
import java.util.HashSet;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class CV0402v01MostarRangoImporteJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public CV0402v01MostarRangoImporteJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
         HashSet<CE0201v01RangoImporte> moLista = new HashSet<>();
         CE0201v01RangoImporte oCERangoImporte = new CE0201v01RangoImporte();
         CD0201v01DataRangoImporte oCDRangoImporte = new CD0201v01DataRangoImporte();
        DefaultTableModel oModeloTabla =  (DefaultTableModel) jTablaRangoValores.getModel();
        
         moLista = oCDRangoImporte.asignarDataRangoImporte();

         Iterator oIt = moLista.iterator();
        int i=0;
         while (oIt.hasNext()){
             i+=1;
            oCERangoImporte = (CE0201v01RangoImporte) oIt.next();
//            System.out.println(oCERangoImporte.getImporteMinimo()+ " " + oCERangoImporte.getImporteMaximo());
            oModeloTabla.addRow(new Object[]{i,oCERangoImporte.getImporteMinimo(), oCERangoImporte.getImporteMaximo()});
         }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaRangoValores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTablaRangoValores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Importe Mínimo", "Importe Máximo"
            }
        ));
        jScrollPane1.setViewportView(jTablaRangoValores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CV0402v01MostarRangoImporteJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CV0402v01MostarRangoImporteJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CV0402v01MostarRangoImporteJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CV0402v01MostarRangoImporteJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CV0402v01MostarRangoImporteJDialog dialog = new CV0402v01MostarRangoImporteJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaRangoValores;
    // End of variables declaration//GEN-END:variables
}
