/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aemsa.mysql.dba.vista;

import aemsa.mysql.controladora.CCTipoInstitucion;
import aemsa.mysql.dba.entidad.CETipoInstitucion;
import aemsa.utilidad.CUTablaBaseArrayList;

import java.util.List;
import java.util.ArrayList;
import javax.swing.table.TableColumn;

/**
 *
 * @author background21
 */
public class JD02v01TablaTipoInstitucion extends javax.swing.JDialog {

    /**
     * Creates new form JD01v01TablaTipoInstitucion
     */
    CUTablaBaseArrayList oCUTablaModelo = new CUTablaBaseArrayList();

    public JD02v01TablaTipoInstitucion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.estructuraTablaTipoInstitucionFinanciera();
        this.cargarTablaTipoInstitucionFinanciera();

    }

    private void estructuraTablaTipoInstitucionFinanciera() {
        //1.0 Asignando el modelo a la tabla creada
        jTblTipoInstitucionFinanciera.setModel(oCUTablaModelo);

        //2.0 Creando columans a la tabla
        oCUTablaModelo.addColumn("Id");
        oCUTablaModelo.addColumn("Código");
        oCUTablaModelo.addColumn("Abreviatura");
        oCUTablaModelo.addColumn("Descripción");
        oCUTablaModelo.addColumn("IdIdioma");

        // 3.0 Proporcionar formato a las columnas
        TableColumn oColumnaId = jTblTipoInstitucionFinanciera.getColumnModel().getColumn(0);
        oColumnaId.setMaxWidth(40);
        oColumnaId.setResizable(false);
        
        TableColumn oColumnaCodigo = jTblTipoInstitucionFinanciera.getColumnModel().getColumn(1);
        oColumnaCodigo.setMaxWidth(50);
        oColumnaCodigo.setResizable(false);
        
        TableColumn oColumnaAbreviatura = jTblTipoInstitucionFinanciera.getColumnModel().getColumn(2);
        oColumnaAbreviatura.setMaxWidth(150);
        oColumnaAbreviatura.setResizable(false);
        
        TableColumn oColumnaDescripcion = jTblTipoInstitucionFinanciera.getColumnModel().getColumn(3);
        oColumnaDescripcion.setMaxWidth(300);
        oColumnaDescripcion.setResizable(false);
        
        TableColumn oColumnaIdIdioma = jTblTipoInstitucionFinanciera.getColumnModel().getColumn(4);
        oColumnaIdIdioma.setMaxWidth(30);
        oColumnaIdIdioma.setResizable(false);

    }

    private void cargarTablaTipoInstitucionFinanciera() {
        ArrayList oaLstTablaModelo;

        try {

            //1.0 Definiendo el modelo de tabla
            CUTablaBaseArrayList oCULstTablaModelo = (CUTablaBaseArrayList) jTblTipoInstitucionFinanciera.getModel();

            //2.0 Cargando la tabla de informacion
            List<CETipoInstitucion> oLstCETipoInstitucionFinanciera = CCTipoInstitucion.cargarTablaTipoInstitucionv1();

            //3.0 Llenando la lista temporal 
            if (oLstCETipoInstitucionFinanciera != null) {
                for (int indice = 0; indice < oLstCETipoInstitucionFinanciera.size(); indice++) {
                    CETipoInstitucion oCETipoInstitucionFinanciera = oLstCETipoInstitucionFinanciera.get(indice);

                    oaLstTablaModelo = new ArrayList();

                    oaLstTablaModelo.add(oCETipoInstitucionFinanciera.getMid_tipo_institucion());
                    oaLstTablaModelo.add(oCETipoInstitucionFinanciera.getMcod_tipo_institucion());
                    oaLstTablaModelo.add(oCETipoInstitucionFinanciera.getMtxt_abrv());
                    oaLstTablaModelo.add(oCETipoInstitucionFinanciera.getMtxt_desc());
                    oaLstTablaModelo.add(oCETipoInstitucionFinanciera.getMid_idioma());

                    //4.0 Asignado información de lista temporal al modelo de tabla
                    oCULstTablaModelo.addRow(oaLstTablaModelo);
                }
            } else {
                this.limpiarTablaTipoInstitucionFinanciera();
            }

        } catch (Exception ex) {
        }
    }

    private void limpiarTablaTipoInstitucionFinanciera() {
        //1.0 Definiendo el modelo de tabla
        CUTablaBaseArrayList oCULstTablaModelo = (CUTablaBaseArrayList) jTblTipoInstitucionFinanciera.getModel();

        for (int indice = 0; indice < oCULstTablaModelo.getRowCount(); indice++) {
            oCULstTablaModelo.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblTipoInstitucionFinanciera = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTblTipoInstitucionFinanciera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblTipoInstitucionFinanciera);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JD02v01TablaTipoInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JD02v01TablaTipoInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JD02v01TablaTipoInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JD02v01TablaTipoInstitucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JD02v01TablaTipoInstitucion dialog = new JD02v01TablaTipoInstitucion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblTipoInstitucionFinanciera;
    // End of variables declaration//GEN-END:variables
}
