/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.aemsa.evalua.swing.view.jcombobox;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import pe.aemsa.evalua.swing.view.jcombobox.entidad.CEAnimal;

/**
 *
 * @author ALDV
 */
public class JDlg0703v01ComboAnimalesMetodoDefaultComboBoxModel extends javax.swing.JDialog {
    private CEAnimal oCEAnimal;
    /**
     * Creates new form JDlg0703v01ComboAnimalesMetodoDefaultComboBoxModel
     */
    public JDlg0703v01ComboAnimalesMetodoDefaultComboBoxModel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // 1. Declarando el componente DefaultComboBoxModel
        DefaultComboBoxModel oModeloCombo = new DefaultComboBoxModel();
        oModeloCombo.removeAllElements();
        JCbxMetodoDefaultComboBoxModel.setModel(oModeloCombo);
        
        oModeloCombo.addElement(new CEAnimal(1, "300", "A300", "Pasquel"));
        
        oCEAnimal = new CEAnimal();
        oCEAnimal.setIdAnimal(2);
        oCEAnimal.setCodigoAnimal("400");
        oCEAnimal.setNumeroArete("A400");
        oCEAnimal.setNombreAlias("Raquel");
        oModeloCombo.addElement(oCEAnimal);
        
        oCEAnimal = new CEAnimal();
        oCEAnimal.setIdAnimal(3);
        oCEAnimal.setCodigoAnimal("500");
        oCEAnimal.setNumeroArete("A500");
        oCEAnimal.setNombreAlias("Pancha");
        oModeloCombo.addElement(oCEAnimal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JCbxMetodoDefaultComboBoxModel = new javax.swing.JComboBox();
        JLblMedotoCombo = new javax.swing.JLabel();
        JLblPosicionCombo = new javax.swing.JLabel();
        JLblDatoObjeto = new javax.swing.JLabel();
        JTxtFPosicionElemento = new javax.swing.JTextField();
        JTxtFDatoObjeto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JCbxMetodoDefaultComboBoxModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCbxMetodoDefaultComboBoxModelMouseClicked(evt);
            }
        });

        JLblMedotoCombo.setText("Metodo DefaultComboBoxModel");

        JLblPosicionCombo.setText("Posición de Elemento");

        JLblDatoObjeto.setText("Dato del Objeto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLblMedotoCombo)
                    .addComponent(JLblPosicionCombo)
                    .addComponent(JLblDatoObjeto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCbxMetodoDefaultComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JTxtFDatoObjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addComponent(JTxtFPosicionElemento, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblMedotoCombo)
                    .addComponent(JCbxMetodoDefaultComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblPosicionCombo)
                    .addComponent(JTxtFPosicionElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblDatoObjeto)
                    .addComponent(JTxtFDatoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCbxMetodoDefaultComboBoxModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCbxMetodoDefaultComboBoxModelMouseClicked
        CEAnimal oAnimal = (CEAnimal) JCbxMetodoDefaultComboBoxModel.getSelectedItem();
        JTxtFPosicionElemento.setText(Integer.toString(JCbxMetodoDefaultComboBoxModel.getSelectedIndex()));
        JTxtFDatoObjeto.setText(oAnimal.getNombreAlias());
    }//GEN-LAST:event_JCbxMetodoDefaultComboBoxModelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg0703v01ComboAnimalesMetodoDefaultComboBoxModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg0703v01ComboAnimalesMetodoDefaultComboBoxModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg0703v01ComboAnimalesMetodoDefaultComboBoxModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg0703v01ComboAnimalesMetodoDefaultComboBoxModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg0703v01ComboAnimalesMetodoDefaultComboBoxModel dialog = new JDlg0703v01ComboAnimalesMetodoDefaultComboBoxModel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void setSelectedValue(JComboBox comboBox, String value)
    {
        CEAnimal item;
        for (int i = 0; i < comboBox.getItemCount(); i++)
        {
            item = (CEAnimal)comboBox.getItemAt(i);
            if (item.getCodigoAnimal().equalsIgnoreCase(value))
            {
                comboBox.setSelectedIndex(i);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JCbxMetodoDefaultComboBoxModel;
    private javax.swing.JLabel JLblDatoObjeto;
    private javax.swing.JLabel JLblMedotoCombo;
    private javax.swing.JLabel JLblPosicionCombo;
    private javax.swing.JTextField JTxtFDatoObjeto;
    private javax.swing.JTextField JTxtFPosicionElemento;
    // End of variables declaration//GEN-END:variables
}
