/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.aemsa.cap29.swing.controls.jlist.vista;

import pe.aemsa.cap29.swing.controls.jlist.vista.impl.CM0801v01RegistroPersona;

/**
 *
 * @author ALDV
 */
public class JDlg0801v01RegistroPersonaConJList extends javax.swing.JDialog {

    /**
     * Creates new form jDlg0101v01RegistroPersonaConJList
     */
    public JDlg0801v01RegistroPersonaConJList(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        CM0801v01RegistroPersona oModeloPersona = new CM0801v01RegistroPersona();
        jLstListaPersona.setModel(oModeloPersona);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPneTitulo = new javax.swing.JPanel();
        jLblTitulo = new javax.swing.JLabel();
        jLPneDatosPersona = new javax.swing.JLayeredPane();
        jLblNombre = new javax.swing.JLabel();
        jLblApellido = new javax.swing.JLabel();
        jLblFechaNacimiento = new javax.swing.JLabel();
        jLblEdad = new javax.swing.JLabel();
        jTxtFNombre = new javax.swing.JTextField();
        jTxtFApellido = new javax.swing.JTextField();
        jLblNumeroEdad = new javax.swing.JLabel();
        jFTxtFFechaNacimiento = new javax.swing.JFormattedTextField();
        jLblSexo = new javax.swing.JLabel();
        jRBtnMasculino = new javax.swing.JRadioButton();
        jRBtnFemenino = new javax.swing.JRadioButton();
        jLblTipoDocumento = new javax.swing.JLabel();
        jCmboxTipoDocumento = new javax.swing.JComboBox<>();
        jLblHobie = new javax.swing.JLabel();
        jCBoxFutbol = new javax.swing.JCheckBox();
        jCBoxTenis = new javax.swing.JCheckBox();
        jCBoxMaraton = new javax.swing.JCheckBox();
        jCBoxCaminata = new javax.swing.JCheckBox();
        jBtnAdicionar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jPneImagenHobie = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLstListaPersona = new javax.swing.JList<>();
        jPneDatosRegistrados = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPneTitulo.setBackground(new java.awt.Color(204, 204, 255));

        jLblTitulo.setText("Registro de Personas");

        javax.swing.GroupLayout jPneTituloLayout = new javax.swing.GroupLayout(jPneTitulo);
        jPneTitulo.setLayout(jPneTituloLayout);
        jPneTituloLayout.setHorizontalGroup(
            jPneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPneTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPneTituloLayout.setVerticalGroup(
            jPneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPneTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitulo)
                .addContainerGap())
        );

        jLPneDatosPersona.setBackground(new java.awt.Color(153, 255, 153));
        jLPneDatosPersona.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLblNombre.setText("Nombre ");

        jLblApellido.setText("Apellidos");

        jLblFechaNacimiento.setText("Fecha Nacimiento");

        jLblEdad.setText("Edad");

        jLblNumeroEdad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jFTxtFFechaNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLblSexo.setText("Sexo");

        jRBtnMasculino.setText("Masculino");
        jRBtnMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnMasculinoActionPerformed(evt);
            }
        });

        jRBtnFemenino.setText("Femenino");

        jLblTipoDocumento.setText("Tipo Documento");

        jCmboxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLblHobie.setText("Hobie");

        jCBoxFutbol.setText("Futbol");

        jCBoxTenis.setText("Tenis");

        jCBoxMaraton.setText("Maraton");
        jCBoxMaraton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxMaratonActionPerformed(evt);
            }
        });

        jCBoxCaminata.setText("Caminata");

        jBtnAdicionar.setText("Adicionar");
        jBtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jPneImagenHobie.setBorder(javax.swing.BorderFactory.createTitledBorder("[ Imagen ] "));

        javax.swing.GroupLayout jPneImagenHobieLayout = new javax.swing.GroupLayout(jPneImagenHobie);
        jPneImagenHobie.setLayout(jPneImagenHobieLayout);
        jPneImagenHobieLayout.setHorizontalGroup(
            jPneImagenHobieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPneImagenHobieLayout.setVerticalGroup(
            jPneImagenHobieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLPneDatosPersona.setLayer(jLblNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jLblApellido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jLblFechaNacimiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jLblEdad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jTxtFNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jTxtFApellido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jLblNumeroEdad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jFTxtFFechaNacimiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jLblSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jRBtnMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jRBtnFemenino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jLblTipoDocumento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jCmboxTipoDocumento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jLblHobie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jCBoxFutbol, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jCBoxTenis, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jCBoxMaraton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jCBoxCaminata, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jBtnAdicionar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jBtnEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPneDatosPersona.setLayer(jPneImagenHobie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLPneDatosPersonaLayout = new javax.swing.GroupLayout(jLPneDatosPersona);
        jLPneDatosPersona.setLayout(jLPneDatosPersonaLayout);
        jLPneDatosPersonaLayout.setHorizontalGroup(
            jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPneDatosPersonaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblEdad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblTipoDocumento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblHobie, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLPneDatosPersonaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLPneDatosPersonaLayout.createSequentialGroup()
                                .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLPneDatosPersonaLayout.createSequentialGroup()
                                        .addComponent(jRBtnMasculino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRBtnFemenino))
                                    .addComponent(jLblNumeroEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTxtFFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCmboxTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addComponent(jPneImagenHobie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLPneDatosPersonaLayout.createSequentialGroup()
                                .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLPneDatosPersonaLayout.createSequentialGroup()
                                        .addComponent(jCBoxFutbol)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCBoxTenis)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCBoxMaraton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCBoxCaminata))
                                    .addGroup(jLPneDatosPersonaLayout.createSequentialGroup()
                                        .addComponent(jBtnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jLPneDatosPersonaLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFNombre)
                            .addComponent(jTxtFApellido))))
                .addContainerGap())
        );
        jLPneDatosPersonaLayout.setVerticalGroup(
            jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPneDatosPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNombre)
                    .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblApellido)
                    .addComponent(jTxtFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLPneDatosPersonaLayout.createSequentialGroup()
                        .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblFechaNacimiento)
                            .addComponent(jFTxtFFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblEdad)
                            .addComponent(jLblNumeroEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblSexo)
                            .addComponent(jRBtnMasculino)
                            .addComponent(jRBtnFemenino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblTipoDocumento)
                            .addComponent(jCmboxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPneImagenHobie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblHobie)
                    .addComponent(jCBoxFutbol)
                    .addComponent(jCBoxTenis)
                    .addComponent(jCBoxMaraton)
                    .addComponent(jCBoxCaminata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLPneDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLstListaPersona.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jLstListaPersona);

        jPneDatosRegistrados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPneDatosRegistradosLayout = new javax.swing.GroupLayout(jPneDatosRegistrados);
        jPneDatosRegistrados.setLayout(jPneDatosRegistradosLayout);
        jPneDatosRegistradosLayout.setHorizontalGroup(
            jPneDatosRegistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPneDatosRegistradosLayout.setVerticalGroup(
            jPneDatosRegistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPneTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLPneDatosPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPneDatosRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPneTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLPneDatosPersona)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPneDatosRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBtnMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBtnMasculinoActionPerformed

    private void jCBoxMaratonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxMaratonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBoxMaratonActionPerformed

    private void jBtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAdicionarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg0801v01RegistroPersonaConJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg0801v01RegistroPersonaConJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg0801v01RegistroPersonaConJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg0801v01RegistroPersonaConJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg0801v01RegistroPersonaConJList dialog = new JDlg0801v01RegistroPersonaConJList(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdicionar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JCheckBox jCBoxCaminata;
    private javax.swing.JCheckBox jCBoxFutbol;
    private javax.swing.JCheckBox jCBoxMaraton;
    private javax.swing.JCheckBox jCBoxTenis;
    private javax.swing.JComboBox<String> jCmboxTipoDocumento;
    private javax.swing.JFormattedTextField jFTxtFFechaNacimiento;
    private javax.swing.JLayeredPane jLPneDatosPersona;
    private javax.swing.JLabel jLblApellido;
    private javax.swing.JLabel jLblEdad;
    private javax.swing.JLabel jLblFechaNacimiento;
    private javax.swing.JLabel jLblHobie;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblNumeroEdad;
    private javax.swing.JLabel jLblSexo;
    private javax.swing.JLabel jLblTipoDocumento;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JList<String> jLstListaPersona;
    private javax.swing.JPanel jPneDatosRegistrados;
    private javax.swing.JPanel jPneImagenHobie;
    private javax.swing.JPanel jPneTitulo;
    private javax.swing.JRadioButton jRBtnFemenino;
    private javax.swing.JRadioButton jRBtnMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtFApellido;
    private javax.swing.JTextField jTxtFNombre;
    // End of variables declaration//GEN-END:variables
}
