/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.aemsa.cap29.swing.controls01.label;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class JDlg0101v01ControlLabel extends javax.swing.JDialog {

    /**
     * Creates new form JDlg0101v01ControlLabel
     */
    public JDlg0101v01ControlLabel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        jLblTituloArquitectura = new JLabel("Iniciando el proceso .....", JLabel.CENTER);
        JOptionPane.showMessageDialog(this, jLblTituloArquitectura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTituloArquitectura = new javax.swing.JLabel();
        jLblArquitecturASO = new javax.swing.JLabel();
        jLblArquitecturaHOST = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblTituloArquitectura.setText("Arquitectura");
        jLblTituloArquitectura.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLblTituloArquitecturaMouseDragged(evt);
            }
        });

        jLblArquitecturASO.setText("Coordenada X");

        jLblArquitecturaHOST.setText("Coordenada Y");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblArquitecturaHOST)
                    .addComponent(jLblArquitecturASO)
                    .addComponent(jLblTituloArquitectura))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLblTituloArquitectura)
                .addGap(18, 18, 18)
                .addComponent(jLblArquitecturASO)
                .addGap(18, 18, 18)
                .addComponent(jLblArquitecturaHOST)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLblTituloArquitecturaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblTituloArquitecturaMouseDragged
        
    }//GEN-LAST:event_jLblTituloArquitecturaMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg0101v01ControlLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg0101v01ControlLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg0101v01ControlLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg0101v01ControlLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg0101v01ControlLabel dialog = new JDlg0101v01ControlLabel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblArquitecturASO;
    private javax.swing.JLabel jLblArquitecturaHOST;
    private javax.swing.JLabel jLblTituloArquitectura;
    // End of variables declaration//GEN-END:variables
}
