@startuml
usecase RegistroSolicitud
usecase VerificarSolicitud
usecase AprobarSolicitud
usecase ProgramarDesembolso
usecase EnviarDesembolsoBanco
usecase RecibirConfirmación
usecase CerrarSolicitud
@enduml
