/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.inverfin.predio.view;

/**
 *
 * @author user
 */
public class CVJDialog0101v01BusquedaDireccion extends javax.swing.JDialog {

    /**
     * Creates new form CVJDialog0101v01BusquedaDireccion
     */
    public CVJDialog0101v01BusquedaDireccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jLabelTituloBusquedaPredio = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jLabelDireccionBusqueda = new javax.swing.JLabel();
        jTextFieldDireccionBusqueda = new javax.swing.JTextField();
        jScrollPaneContribuyente = new javax.swing.JScrollPane();
        jTableContribuyente = new javax.swing.JTable();
        jButtonProcesarBusqueda = new javax.swing.JButton();
        jButtonGenerarPDF = new javax.swing.JButton();
        jLabelTipoPredio = new javax.swing.JLabel();
        jCheckBoxHR = new javax.swing.JCheckBox();
        jCheckBoxHP = new javax.swing.JCheckBox();
        jPanelFoot = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".....[ Modulo de Predio ].....");
        setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanelHeader.setBackground(new java.awt.Color(102, 102, 255));
        jPanelHeader.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabelTituloBusquedaPredio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTituloBusquedaPredio.setText("Búsqueda de Predios por Dirección");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloBusquedaPredio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloBusquedaPredio)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelBody.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabelDireccionBusqueda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDireccionBusqueda.setText("Dirección de búsqueda : ");

        jTextFieldDireccionBusqueda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jTableContribuyente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableContribuyente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTableContribuyente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Contribuyente", "N° Predio", "Check"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneContribuyente.setViewportView(jTableContribuyente);
        if (jTableContribuyente.getColumnModel().getColumnCount() > 0) {
            jTableContribuyente.getColumnModel().getColumn(0).setResizable(false);
            jTableContribuyente.getColumnModel().getColumn(1).setResizable(false);
            jTableContribuyente.getColumnModel().getColumn(2).setResizable(false);
            jTableContribuyente.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonProcesarBusqueda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonProcesarBusqueda.setText(".....");

        jButtonGenerarPDF.setText("Generar PDF");

        jLabelTipoPredio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTipoPredio.setText("Tipo Predio : ");

        jCheckBoxHR.setText("HR");

        jCheckBoxHP.setText("HP");

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneContribuyente)
                            .addGroup(jPanelBodyLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabelTipoPredio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBoxHR)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHP)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBodyLayout.createSequentialGroup()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelBodyLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonGenerarPDF))
                            .addGroup(jPanelBodyLayout.createSequentialGroup()
                                .addComponent(jLabelDireccionBusqueda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDireccionBusqueda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonProcesarBusqueda)))
                        .addGap(36, 36, 36))))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccionBusqueda)
                    .addComponent(jTextFieldDireccionBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProcesarBusqueda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoPredio)
                    .addComponent(jCheckBoxHR)
                    .addComponent(jCheckBoxHP)
                    .addComponent(jButtonGenerarPDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneContribuyente, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
        );

        jPanelFoot.setBackground(new java.awt.Color(153, 255, 153));
        jPanelFoot.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanelFoot.setPreferredSize(new java.awt.Dimension(0, 50));

        javax.swing.GroupLayout jPanelFootLayout = new javax.swing.GroupLayout(jPanelFoot);
        jPanelFoot.setLayout(jPanelFootLayout);
        jPanelFootLayout.setHorizontalGroup(
            jPanelFootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
        jPanelFootLayout.setVerticalGroup(
            jPanelFootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFoot, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CVJDialog0101v01BusquedaDireccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CVJDialog0101v01BusquedaDireccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CVJDialog0101v01BusquedaDireccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CVJDialog0101v01BusquedaDireccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CVJDialog0101v01BusquedaDireccion dialog = new CVJDialog0101v01BusquedaDireccion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarPDF;
    private javax.swing.JButton jButtonProcesarBusqueda;
    private javax.swing.JCheckBox jCheckBoxHP;
    private javax.swing.JCheckBox jCheckBoxHR;
    private javax.swing.JLabel jLabelDireccionBusqueda;
    private javax.swing.JLabel jLabelTipoPredio;
    private javax.swing.JLabel jLabelTituloBusquedaPredio;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelFoot;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPaneContribuyente;
    private javax.swing.JTable jTableContribuyente;
    private javax.swing.JTextField jTextFieldDireccionBusqueda;
    // End of variables declaration//GEN-END:variables
}
